In [15]:
import numpy as np
import pandas as pd

In [16]:
flats = pd.read_csv('flats_cleaned.csv')
houses = pd.read_csv('house_cleaned.csv')

In [17]:
df = pd.concat([flats,houses],ignore_index=True)

In [18]:
df = df.sample(df.shape[0]).reset_index(drop=True)

In [19]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 37C Gurgaon,flat,ild greens,0.90,5614.0,1603.0,Super Built up area 1603(148.92 sq.m.)Built Up...,3,3,3,not available,"Ground Floor, Sector 37C Gurgaon, Gurgaon, Har...",0.0,North-East,Under Construction,"['The Esplanade Mall', 'Gurgaon Road', 'Delhi ...","Good location with hospital, school close by.",NaN,"['Lift(s)', 'Feng Shui / Vaastu Compliant', 'I...","['Green Area5 out of 5', 'Construction5 out of..."
1,3 BHK Flat in Sector 99A Gurgaon,flat,pareena coban residences,1.40,7010.0,1997.0,Super Built up area 1997(185.53 sq.m.),3,5,3+,not available,"Sector 99A Gurgaon, Gurgaon, Haryana",6.0,NaN,0 to 1 Year Old,"['Gopal Super Market', 'Little Need Super Mark...",Newly constructed apartment with all amenities,[],"['Swimming Pool', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle3 out of 5..."
2,3 BHK Flat in Sector 104 Gurgaon,flat,hero homes,1.75,10361.0,1689.0,Super Built up area 1689(156.91 sq.m.),3,3,3,not available,"Sector 104 Gurgaon, Gurgaon, Haryana",2.0,NaN,Dec 2024,"['Basai Metro Station', 'HUDA Market', 'Dwarka...",Residential apartment for sell.Located in sect...,NaN,"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,3 Bedroom House for sale in Sector 26 Gurgaon,house,dlf city phase 1,3.25,33129.0,981.0,Plot area 109(91.14 sq.m.),3,3,3,study room,"Sector 26 Gurgaon, Gurgaon, Haryana",2.0,West,10+ Year Old,"['Dlf phase 1 metro station', 'Sikandarpur met...","Residential house, e block, dlf phase-1, gurga...","['5 Fan', '16 Light', 'No AC', 'No Bed', 'No C...","['Feng Shui / Vaastu Compliant', 'Private Gard...",NaN
4,2 BHK Flat in Sector 79 Gurgaon,flat,godrej,1.41,9000.0,1567.0,Carpet area: 1572 (146.04 sq.m.),2,2,3,study room,"Sector 79 Gurgaon, Gurgaon, Haryana",3.0,NaN,0 to 1 Year Old,"['Vatika Town Square-INXT', 'Naurangpur Road',...","It's a new society, ready to move. Complementa...",NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of..."

In [20]:
df.to_csv('gurgaon_properties.csv',index=False)